### ISSUE TITLE
Improve documents

### ISSUE THREAD

**Issue by oooFUNooo** [matanki-saito/EU4JPModCore#1]
現在の導入スライドの問題点を列挙します。

2ページ目：
- [x] A. URLが直接クリックできない。
- [x] B. そもそもURLを文字として表示する必要はない。
- [x] C. zipという表現はわかりにくい。
- [x] D. 解凍という表現はわかりにくい（展開でも同じ）
- [x] E. zipファイルを展開する方法から説明した方が良い。

3ページ目：
- [x] A. 2ページ目のCとDとEは3ページ目も共通。
- [x] B. 設定によってはシングルクリックで起動する場合を考慮した方が良い。
- [x] C. スクリーンショットを入れるのならば、拡張子が表示されない環境にも配慮した方が良い。
- [x] D. アラートという表現ではなにを指しているのかわからない。
（アラートという名前のダイアログが出るわけではないため。具体的な画像が必要）

4ページ目：
- [x] A. CK2と混乱しないように「上の」「黄色の」などの説明を入れた方が良い。

5ページ目：
- [x] A. 4ページ目のAは5ページ目も共通。
- [x] B. 日本語化の「化」が抜けている。

6ページ目：
- [x] A. おそらく「Subはお好みで」を読んだユーザーは困惑する。結局、詳細を確認するしかない。
（最小限の判断基準を示すか、チェックする必要はないと明言した方が良い）

7ページ目：
- [x] A. 連絡先がわかりにくすぎる。連絡して欲しくないようにしか見えない。
（文字をもっと大きく。ブラウザでもアクセスできることを明記し、そのリンクを直接貼ること）
（連絡先は広報サイトの掲示板へ誘導しても構わない）

8ページ目：
- [x] A. 鉄人モードがなにを示すのかの説明が不足している。
（最低限、Steamの実績が取れることと、セーブ＆ロードが制限されることの説明が必要）

9ページ目：
- [x] A.「一部の地名」がどの範囲を指しているのかが曖昧。
（詳細説明なのだから、文化によって地名が変化する仕様を説明しても良いのでは？）
- [x] B. 現状「キャラクター名」も一部にしか対応していないので、それを明記した方が良い。

**Comment by matanki-saito** [comment]
日本語化の説明なので、鉄人モードについては実績が取れないだけを追加しました。

**Comment by oooFUNooo** [comment]
修正を確認しました。
良くなったと思いますが、まだ気になる箇所があるので、以下に列挙します。
非常に細かい指摘もありますが、最終的なブラッシュアップを兼ねていますのでご了承ください。

全体：
- [x] 文の周囲を囲む点線が説明を読みにくくしている。
（なにもない方が良いが、あえて囲むのなら実線の方が良い）
- [ ] スライド下部の▼を押すと表示される目次に、適当な名前が表示されている。
- [x] カタカナ語の末尾の長音記号（ー）が省略される傾向がある。
（エンジニアとしては正しいが、一般的な表現を用いた方が良い。キャラクタ→キャラクターなど）
- [x] PCを操作しながらスマホやタブレットで閲覧するユーザーも念頭に置いた方が良い。
（スライド間の移動に「ここをクリック」などの表現は避ける）

1ページ目：
- [x] 「EUVI」とローマ数字になっている。

2ページ目：
- [x] ブラウザがウイルス警告を出した場合の説明を入れた方が良いのでは？
- [x] ファイル解凍方法のリンク先がWindows Vista/7のページになっていたが問題ないか？

3ページ目：
- [x] （ダブル）は不要。
- [x] スクリーンショットの上半分（中途半端に映っているエクスプローラー）は不要。
（入れるのであれば、エクスプローラーであることがわかるようにした方が良い）

4ページ目：
- [x] 前のページに続き「2/5」が2回出てきている。
- [x] 図は問題ないが、文字による説明が一切ないのは不親切。

7ページ目：
- [x] 「MOD」がすべて大文字になっている。
- [x] スクリーンショットの左上にSteamの通知が重なっているが問題ないか？

8ページ目：
- [x] 注意は「ご注意」などと柔らかい表現にした方が良い。赤文字なので両側の「！」は不要。
- [x] 前のページで読むのをやめる人が多いと予想されるので、読んでもらうための工夫が必要。
（7ページ目に組み込むなど）

10ページ目：
- [x] 「MOD」がすべて大文字になっている箇所がある。

11ページ目：
- [x] 「MOD」がすべて大文字になっている箇所がある。
- [x] 「ブロビンス」は「州」と書き換えるべき。
（日本語化Modではブロビンスという表現を用いていない）
- [x] 文化によって地名が変化する例が不適切。
（オスマンがコンスタンティノープルを支配しても、それだけではイスタンブールに変化しない）

**Comment by oooFUNooo** [comment]
上の指摘から、特にリリースまでに修正を要する箇所を抜き出します。

2ページ目：
 - [x] ブラウザがウイルス警告を出した場合の説明を入れた方が良いのでは？
 - [x] ファイル解凍方法のリンク先がWindows Vista/7のページになっていたが問題ないか？

4ページ目：
 - [x]  図は問題ないが、文字による説明が一切ないのは不親切。

8ページ目：
 - [x] 前のページで読むのをやめる人が多いと予想されるので、読んでもらうための工夫が必要。
（7ページ目に組み込むなど）

**Comment by matanki-saito** [comment]
州変化の例は何がいいでしょうか。

**Comment by matanki-saito** [comment]
>スマホやタブレット
Steamでのインストールなので、PCで導入スライドをみることしかありえないと思っていたのですが、どのような場合で想定されますか？またクリックを言い換えるとすればどうなりますか？

**Comment by oooFUNooo** [comment]
・州の名前が変化する例
　プレイヤーが日本人なので、現在の説明に用いているアイヌ人と北海道の例でいいと思います。
（具体的な地名を出してもわかる人はまずいないので、地名そのものを書く必要はありません）

・スマホやタブレットの場合
　PCでSteam/EU4を操作しながら、スマホやタブレットのブラウザで日本語化の説明を読む場合が
　考えられます。スマホやタブレットを第2のディスプレイとして使う場合です。
　言い換えるとしたら「ここを選択して」「このリンクをたどって」のような形が考えられます。

**Comment by matanki-saito** [comment]
>スライド下部の▼を押すと表示される目次に、適当な名前が表示されている。

この部分は自動で埋まっているので、任意に変更できるか確認します

**Comment by matanki-saito** [comment]
州名変更の例文変更しました。スライド下部の▼はちょっと変更難しかったので一旦これでどうでしょう 🙇

**Comment by oooFUNooo** [comment]
良いんじゃないでしょうか。
リリース時にはこれでいきましょう。
