### ISSUE TITLE
Text Overflow in Country Religious View

### ISSUE THREAD

**Issue by oooFUNooo** [matanki-saito/EU4JPModCore#4]
問題：
宗教タブでイスラム教の学派名が文字あふれを起こしている。

再現性：
常に

再現手順：
1. 1444年のムシャーシャ（ペルシャ湾にある国）で開始。
2. 宗教タブを開き、学派（イスマーイール派）を確認する。

原因：
日本語訳の文字数が原文よりも多いため。

解決策：
`interface/countryreligionview.gui`の380行目以下を以下のように修正する。

`x = 50` → `x = 85`
`font = "vic_18"` → `font = "Main_16"`
`format = right` → `format = center`

参考画像：
フォントを変更しているが、日本語化Mod標準でも同じ。

不具合の状況
![A](https://user-images.githubusercontent.com/42687608/74669861-5d239980-51eb-11ea-9d17-6eb7b6963075.jpg)

位置を調整しても解決にならない
![B](https://user-images.githubusercontent.com/42687608/74669991-9b20bd80-51eb-11ea-8b52-522b6c31fad8.jpg)
![C](https://user-images.githubusercontent.com/42687608/74670007-a1169e80-51eb-11ea-8299-98e6d841a6b5.jpg)

フォントサイズも変えると解決する
![D](https://user-images.githubusercontent.com/42687608/74670044-b4296e80-51eb-11ea-99ce-086a0dba453c.jpg)
![E](https://user-images.githubusercontent.com/42687608/74670057-b8558c00-51eb-11ea-99bd-00771bc168b3.jpg)

**Comment by matanki-saito** [comment]
対応しました。
fontのみ、表示が見切れてしまったので、更に小さいArial12にしています。
formatはcenterとcentreの２つがあるようですが、centerにしました
